<a href="https://colab.research.google.com/github/TKhahahah/Text_Analytics/blob/main/Copy_of_Data_Analytics_and_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mini Project 2: Data Analytics and Modeling

<img src="https://datarundown.com/wp-content/uploads/2023/05/Model-Data-Analytics.jpg" width="400px">

ชื่อกลุ่ม: ...

รายชื่อสมาชิก การแบ่งงาน และสัดส่วนในการทำงาน:
1. ...
2. ...
3. ...
4. ...

กำหนดส่ง: ศุกร์ 24 ตุลาคม 2568  

รายงานในชั้นเรียน: เสาร์ 25 ตุลาคม 2568

** NOTE **
* อย่าลืมบันทึกงานที่ทำในโน้ตบุ๊คนี้เป็นประจำขณะทำงาน มิเช่นนั้นงานที่ทำอยู่อาจสูญหายได้
* **เริ่มทำแต่เนิ่น ๆ อย่ารอที่จะทำก่อนส่ง เพราะจะทำไม่เสร็จ เนื่องจากปัญหามากมายที่จะเกิดขึ้นระหว่างการทำงาน และอาจารย์ไม่รับปรึกษาในคืนก่อนส่ง**
----------------------

### เลือกชุดข้อมูล 1 ชุดจากข้อมูลที่กำหนดให้ต่อไปนี้
* <b>MovieLens 1M Data Set<b>
    * ข้อมูลชุดนี้มีข้อมูลเกี่ยวกับ movies, users, และ how they rate the movies
    * สามารถดูรายละเอียดได้ที่ http://grouplens.org/datasets/movielens/
    * Download the 1 million ratings data set from https://grouplens.org/datasets/movielens/1m/
    * Merge all of the data into a single Pandas DataFrame. See
        * https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html
    
* <b>Walmart_Sales_Forecast<b>
    * สามารถดูรายละเอียดได้ที่ https://github.com/Asikpalysik/Walmart_Sales_Forecast/tree/main
    * ข้อมูลประกอบด้วยไฟล์ features.csv, stores.csv และ ข้อมูลยอดขาย (train.csv และ test.csv)
    * ให้ใช้ข้อมูลจากทุกไฟล์ทุกอย่างประกอบกันในการวิเคราะห์
    
* <b>NYC Taxi Trips<b>
    * ข้อมูลทริปของแท็กซี่ในเมืองนิวยอร์กจาก https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page
    * ข้อมูลเก็บโดย The NYC Taxi and Limousine Commission (TLC) ประกอบด้วย pick-up and drop-off dates/times, pick-up and drop-off locations, trip distances, itemized fares, rate types, payment types, and driver-reported passenger counts
    * นอกจากไฟล์ข้อมูลทริปของแท็กซี่แล้ว ยังมีข้อมูลเกี่ยวกับ zone ของพื้นที่ที่ให้บริการ และคำอธิบายข้อมูลในส่วนล่างสุดของหน้าเดียวกัน
    * ให้ศึกษาข้อมูลการเดินทางของแท็กซี่เหลืองหรือแท็กซี่เขียวในช่วงหนึ่ง (เช่น 1 เดือน หรือ 1 ปีที่ผ่านมา เป็นต้น)
    * ตัวอย่างการอ่านไฟล์ parquet
    ```python
    # install this module to read .parquet files
    !pip install pyarrow
    import pyarrow.parquet as pq
    trips = pq.read_table('yellow_tripdata_2023-09.parquet')
    trips = trips.to_pandas()
    trips
    ```
    
----------------------------------

### ศึกษาข้อมูลที่เลือกใช้ แล้วทำการ
* Tell story about data อธิบายลักษณะของข้อมูล ทำความเข้าใจเกี่ยวกับข้อมูลชุดนี้ ด้วยสถิติ และนำเสนอด้วยแผนภาพ แผนภูมิ หรือกราฟต่าง ๆ
* ตั้ง<span style="color:red">*ปัญหาหรือคำถามเชิงองค์กรหรือธุรกิจ*</span>ที่กลุ่มท่านสนใจเกี่ยวกับข้อมูลนี้ แล้วทำการคาดการณ์ (conjectures) เกี่ยวกับ<span style="color:red">*ปัญหาหรือคำถาม*</span>ที่ได้ตั้งไว้อย่างน้อย 3 ข้อ แล้วสนับสนุนหรือปฏิเสธข้อคาดการณ์ด้วยการวิเคราะห์ข้อมูลหรือด้วย data visualization
    * ปัญหาที่สนใจมีความสำคัญอย่างไร?
    * ข้อคาดการณ์ของท่านจะนำไปสู่การแก้ไขปัญหาหรือตอบคำถามอย่างไร?
* สร้างตัวแบบทำนายโดยใช้ข้อมูลที่เลือกในการตอบปัญหาหรือคำถาม
    * prepare data
    * feature engineering
    * partition data (consider class if any)
    * handle imbalance data
    * build model
      * hyperparameter tuning
    * test model

#### ปัญหา/คำถามที่สนใจคืออะไร
...

#### ปัญหา/คำถามที่สนใจมีความสำคัญอย่างไร?
...

#### ข้อคาดการณ์ของท่านจะนำไปสู่การแก้ไขปัญหาหรือตอบคำถาม
1. ...
2. ...
3. ...
4. (Optional)
5. (Optional)

## Data Loading

In [1]:
# Load data

# Merge data if necessary
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
!pip install pyarrow
import pyarrow.parquet as pq

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [27]:
oct_ytaxi = pq.read_table('/content/drive/MyDrive/DTW2/yellow_tripdata_2024-10.parquet')
oct_ytaxi = oct_ytaxi.to_pandas()
oct_ytaxi

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-10-01 00:30:44,2024-10-01 00:48:26,1.0,3.00,1.0,N,162,246,1,18.40,1.0,0.5,1.50,0.00,1.0,24.90,2.5,0.0
1,1,2024-10-01 00:12:20,2024-10-01 00:25:25,1.0,2.20,1.0,N,48,236,1,14.20,3.5,0.5,3.80,0.00,1.0,23.00,2.5,0.0
2,1,2024-10-01 00:04:46,2024-10-01 00:13:52,1.0,2.70,1.0,N,142,24,1,13.50,3.5,0.5,3.70,0.00,1.0,22.20,2.5,0.0
3,1,2024-10-01 00:12:10,2024-10-01 00:23:01,1.0,3.10,1.0,N,233,75,1,14.20,3.5,0.5,2.00,0.00,1.0,21.20,2.5,0.0
4,1,2024-10-01 00:30:22,2024-10-01 00:30:39,1.0,0.00,1.0,N,262,262,3,3.00,3.5,0.5,0.00,0.00,1.0,8.00,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3833766,2,2024-10-31 23:49:01,2024-11-01 00:04:31,NaN,3.49,NaN,None,107,262,0,21.36,0.0,0.5,0.00,0.00,1.0,25.36,NaN,NaN
3833767,2,2024-10-31 23:35:15,2024-10-31 23:52:50,NaN,2.40,NaN,None,137,145,0,21.88,0.0,0.5,6.03,11.14,1.0,43.05,NaN,NaN
3833768,2,2024-10-31 23:30:43,2024-11-01 00:08:12,NaN,12.28,NaN,None,188,233,0,42.68,0.0,0.5,0.00,6.94,1.0,53.62,NaN,NaN
3833769,2,2024-10-31 23:00:00,2024-10-31 23:06:00,NaN,0.56,NaN,None,230,50,0,16.84,0.0,0.5,0.00,0.00,1.0,20.84,NaN,NaN
3833770,2,2024-10-31 23:18:00,2024-10-31 23:51:00,NaN,6.25,NaN,None,246,75,0,25.96,0.0,0.5,0.00,0.00,1.0,29.96,NaN,NaN

In [28]:
nov_ytaxi = pq.read_table('/content/drive/MyDrive/DTW2/yellow_tripdata_2024-11.parquet')
nov_ytaxi = nov_ytaxi.to_pandas()
nov_ytaxi

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-11-01 00:46:24,2024-11-01 00:57:17,1.0,1.93,1.0,N,239,262,2,-12.80,-1.0,-0.5,0.00,0.00,-1.0,-17.80,-2.5,0.0
1,2,2024-11-01 00:46:24,2024-11-01 00:57:17,1.0,1.93,1.0,N,239,263,2,12.80,1.0,0.5,0.00,0.00,1.0,17.80,2.5,0.0
2,1,2024-11-01 00:37:36,2024-11-01 01:28:36,1.0,34.30,5.0,N,219,265,1,259.00,0.0,0.0,15.00,0.00,1.0,275.00,0.0,0.0
3,2,2024-11-01 00:12:55,2024-11-01 00:22:17,2.0,0.93,1.0,N,186,107,1,10.00,1.0,0.5,1.00,0.00,1.0,16.00,2.5,0.0
4,2,2024-11-01 00:54:45,2024-11-01 00:59:47,1.0,0.38,1.0,N,79,79,1,6.50,1.0,0.5,1.00,0.00,1.0,12.50,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3646364,2,2024-11-30 23:11:15,2024-11-30 23:19:33,NaN,1.09,NaN,None,162,142,0,1.00,0.0,0.5,0.00,0.00,1.0,5.00,NaN,NaN
3646365,1,2024-11-30 23:49:30,2024-12-01 00:27:39,NaN,20.10,NaN,None,132,238,0,70.00,0.0,0.5,8.09,6.94,1.0,89.03,NaN,NaN
3646366,2,2024-11-30 23:31:46,2024-12-01 00:04:32,NaN,1.38,NaN,None,100,230,0,18.71,0.0,0.5,0.00,0.00,1.0,22.71,NaN,NaN
3646367,2,2024-11-30 23:41:21,2024-11-30 23:53:20,NaN,2.63,NaN,None,42,75,0,13.26,0.0,0.5,0.00,0.00,1.0,14.76,NaN,NaN
3646368,2,2024-11-30 23:21:52,2024-11-30 23:31:11,NaN,1.16,NaN,None,116,42,0,-0.50,0.0,0.5,0.00,0.00,1.0,1.00,NaN,NaN

In [29]:
dec_ytaxi = pq.read_table('/content/drive/MyDrive/DTW2/yellow_tripdata_2024-12.parquet')
dec_ytaxi = dec_ytaxi.to_pandas()
dec_ytaxi

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-12-01 00:12:27,2024-12-01 00:31:12,1.0,9.76,1.0,N,138,33,1,38.00,6.0,0.5,4.72,0.00,1.0,51.97,0.0,1.75
1,2,2024-11-30 23:56:04,2024-12-01 00:28:15,1.0,7.62,1.0,N,158,42,1,37.30,1.0,0.5,8.46,0.00,1.0,50.76,2.5,0.00
2,2,2024-12-01 00:50:35,2024-12-01 01:24:46,4.0,20.07,2.0,N,132,236,2,70.00,0.0,0.5,0.00,6.94,1.0,82.69,2.5,1.75
3,2,2024-12-01 00:18:16,2024-12-01 00:33:16,3.0,2.34,1.0,N,142,186,1,15.60,1.0,0.5,4.12,0.00,1.0,24.72,2.5,0.00
4,2,2024-12-01 00:56:13,2024-12-01 01:18:25,1.0,5.05,1.0,N,107,80,1,26.80,1.0,0.5,5.00,0.00,1.0,36.80,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3668366,2,2024-12-31 23:32:00,2024-12-31 23:56:00,NaN,10.71,NaN,None,16,7,0,-4.13,0.0,0.5,0.00,0.00,1.0,-2.63,NaN,NaN
3668367,2,2024-12-31 23:05:00,2024-12-31 23:18:00,NaN,4.56,NaN,None,252,16,0,-1.68,0.0,0.5,0.00,0.00,1.0,-0.18,NaN,NaN
3668368,2,2024-12-31 23:03:16,2024-12-31 23:28:35,NaN,3.94,NaN,None,181,255,0,4.46,0.0,0.5,5.19,0.00,1.0,11.15,NaN,NaN
3668369,1,2024-12-31 23:15:33,2024-12-31 23:36:29,NaN,4.20,NaN,None,165,61,0,27.07,0.0,0.5,0.00,0.00,1.0,28.57,NaN,NaN
3668370,2,2024-12-31 23:04:36,2024-12-31 23:33:34,NaN,5.76,NaN,None,225,114,0,2.17,0.0,0.5,0.00,0.00,1.0,6.17,NaN,NaN

In [30]:
zone_location = pd.read_csv('/content/drive/MyDrive/DTW2/taxi_zone_lookup.csv')
zone_location

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                      NaN          NaN
264         265            NaN           Outside of NYC          NaN

[265 rows x 4 columns]

รวมข้อมูล 3 เดือน และ drop คอลัมน์ที่ไม่ได้ใช้ออก

In [31]:
quarters4_ytaxi = pd.concat([oct_ytaxi, nov_ytaxi, dec_ytaxi], ignore_index=True) #รวมหัวมูลแบบแนวตั้งเนื่องจากมีคอลัมน์เหมือนกัน

quarters4_ytaxi

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-10-01 00:30:44,2024-10-01 00:48:26,1.0,3.00,1.0,N,162,246,1,18.40,1.0,0.5,1.50,0.0,1.0,24.90,2.5,0.0
1,1,2024-10-01 00:12:20,2024-10-01 00:25:25,1.0,2.20,1.0,N,48,236,1,14.20,3.5,0.5,3.80,0.0,1.0,23.00,2.5,0.0
2,1,2024-10-01 00:04:46,2024-10-01 00:13:52,1.0,2.70,1.0,N,142,24,1,13.50,3.5,0.5,3.70,0.0,1.0,22.20,2.5,0.0
3,1,2024-10-01 00:12:10,2024-10-01 00:23:01,1.0,3.10,1.0,N,233,75,1,14.20,3.5,0.5,2.00,0.0,1.0,21.20,2.5,0.0
4,1,2024-10-01 00:30:22,2024-10-01 00:30:39,1.0,0.00,1.0,N,262,262,3,3.00,3.5,0.5,0.00,0.0,1.0,8.00,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11148506,2,2024-12-31 23:32:00,2024-12-31 23:56:00,NaN,10.71,NaN,None,16,7,0,-4.13,0.0,0.5,0.00,0.0,1.0,-2.63,NaN,NaN
11148507,2,2024-12-31 23:05:00,2024-12-31 23:18:00,NaN,4.56,NaN,None,252,16,0,-1.68,0.0,0.5,0.00,0.0,1.0,-0.18,NaN,NaN
11148508,2,2024-12-31 23:03:16,2024-12-31 23:28:35,NaN,3.94,NaN,None,181,255,0,4.46,0.0,0.5,5.19,0.0,1.0,11.15,NaN,NaN
11148509,1,2024-12-31 23:15:33,2024-12-31 23:36:29,NaN,4.20,NaN,None,165,61,0,27.07,0.0,0.5,0.00,0.0,1.0,28.57,NaN,NaN
11148510,2,2024-12-31 23:04:36,2024-12-31 23:33:34,NaN,5.76,NaN,None,225,114,0,2.17,0.0,0.5,0.00,0.0,1.0,6.17,NaN,NaN

In [32]:
import pandas as pd

# รายชื่อคอลัมน์ที่ไม่จำเป็น — สามารถปรับตามจริงได้
cols_to_drop = [
    'store_and_fwd_flag', # flag การเก็บข้อมูล (ไม่ค่อยใช้ในการวิเคราะห์)
    'improvement_surcharge', # ค่าธรรมเนียมเล็กน้อยซ้ำซ้อนกับ fare_amount
    'extra'               # ค่าเพิ่มเติมอื่น ๆ ที่ไม่ใช้วิเคราะห์
]

# ลบคอลัมน์ที่ไม่จำเป็น (ถ้ามี)
quarters4_ytaxi.drop(columns=[c for c in cols_to_drop if c in quarters4_ytaxi.columns],
                     inplace=True)

# ตรวจสอบผลลัพธ์
print("Remaining columns:", list(quarters4_ytaxi.columns))
print("Data shape:", quarters4_ytaxi.shape)

Remaining columns: ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'mta_tax', 'tip_amount', 'tolls_amount', 'total_amount', 'congestion_surcharge', 'Airport_fee']
Data shape: (11148511, 16)

In [33]:
quarters4_ytaxi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11148511 entries, 0 to 11148510
Data columns (total 16 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   PULocationID           int32
 7   DOLocationID           int32
 8   payment_type           int64
 9   fare_amount            float64
 10  mta_tax                float64
 11  tip_amount             float64
 12  tolls_amount           float64
 13  total_amount           float64
 14  congestion_surcharge   float64
 15  Airport_fee            float64
dtypes: datetime64[us](2), float64(10), int32(3), int64(1)
memory usage: 1.2 GB

In [34]:
print(quarters4_ytaxi.columns)

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'PULocationID',
       'DOLocationID', 'payment_type', 'fare_amount', 'mta_tax', 'tip_amount',
       'tolls_amount', 'total_amount', 'congestion_surcharge', 'Airport_fee'],
      dtype='object')

In [35]:
quarters4_ytaxi

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,mta_tax,tip_amount,tolls_amount,total_amount,congestion_surcharge,Airport_fee
0,2,2024-10-01 00:30:44,2024-10-01 00:48:26,1.0,3.00,1.0,162,246,1,18.40,0.5,1.50,0.0,24.90,2.5,0.0
1,1,2024-10-01 00:12:20,2024-10-01 00:25:25,1.0,2.20,1.0,48,236,1,14.20,0.5,3.80,0.0,23.00,2.5,0.0
2,1,2024-10-01 00:04:46,2024-10-01 00:13:52,1.0,2.70,1.0,142,24,1,13.50,0.5,3.70,0.0,22.20,2.5,0.0
3,1,2024-10-01 00:12:10,2024-10-01 00:23:01,1.0,3.10,1.0,233,75,1,14.20,0.5,2.00,0.0,21.20,2.5,0.0
4,1,2024-10-01 00:30:22,2024-10-01 00:30:39,1.0,0.00,1.0,262,262,3,3.00,0.5,0.00,0.0,8.00,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11148506,2,2024-12-31 23:32:00,2024-12-31 23:56:00,NaN,10.71,NaN,16,7,0,-4.13,0.5,0.00,0.0,-2.63,NaN,NaN
11148507,2,2024-12-31 23:05:00,2024-12-31 23:18:00,NaN,4.56,NaN,252,16,0,-1.68,0.5,0.00,0.0,-0.18,NaN,NaN
11148508,2,2024-12-31 23:03:16,2024-12-31 23:28:35,NaN,3.94,NaN,181,255,0,4.46,0.5,5.19,0.0,11.15,NaN,NaN
11148509,1,2024-12-31 23:15:33,2024-12-31 23:36:29,NaN,4.20,NaN,165,61,0,27.07,0.5,0.00,0.0,28.57,NaN,NaN
11148510,2,2024-12-31 23:04:36,2024-12-31 23:33:34,NaN,5.76,NaN,225,114,0,2.17,0.5,0.00,0.0,6.17,NaN,NaN

## Data Preparation

In [14]:
# Explore variables and check data quality

# Handle missing values, outliers, and noises

# Perform feature engineering (optional)

In [36]:
quarters4_ytaxi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11148511 entries, 0 to 11148510
Data columns (total 16 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   PULocationID           int32
 7   DOLocationID           int32
 8   payment_type           int64
 9   fare_amount            float64
 10  mta_tax                float64
 11  tip_amount             float64
 12  tolls_amount           float64
 13  total_amount           float64
 14  congestion_surcharge   float64
 15  Airport_fee            float64
dtypes: datetime64[us](2), float64(10), int32(3), int64(1)
memory usage: 1.2 GB

In [39]:
# Check for missing values
print("Missing values per column:")
print(quarters4_ytaxi.isnull().any())

# Check for duplicate rows
print("\nNumber of duplicate rows:")
print(quarters4_ytaxi.duplicated().sum())

Missing values per column:
VendorID                 False
tpep_pickup_datetime     False
tpep_dropoff_datetime    False
passenger_count           True
trip_distance            False
RatecodeID                True
PULocationID             False
DOLocationID             False
payment_type             False
fare_amount              False
mta_tax                  False
tip_amount               False
tolls_amount             False
total_amount             False
congestion_surcharge      True
Airport_fee               True
dtype: bool

Number of duplicate rows:
2

In [40]:
quarters4_ytaxi

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,mta_tax,tip_amount,tolls_amount,total_amount,congestion_surcharge,Airport_fee
0,2,2024-10-01 00:30:44,2024-10-01 00:48:26,1.0,3.00,1.0,162,246,1,18.40,0.5,1.50,0.0,24.90,2.5,0.0
1,1,2024-10-01 00:12:20,2024-10-01 00:25:25,1.0,2.20,1.0,48,236,1,14.20,0.5,3.80,0.0,23.00,2.5,0.0
2,1,2024-10-01 00:04:46,2024-10-01 00:13:52,1.0,2.70,1.0,142,24,1,13.50,0.5,3.70,0.0,22.20,2.5,0.0
3,1,2024-10-01 00:12:10,2024-10-01 00:23:01,1.0,3.10,1.0,233,75,1,14.20,0.5,2.00,0.0,21.20,2.5,0.0
4,1,2024-10-01 00:30:22,2024-10-01 00:30:39,1.0,0.00,1.0,262,262,3,3.00,0.5,0.00,0.0,8.00,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11148506,2,2024-12-31 23:32:00,2024-12-31 23:56:00,NaN,10.71,NaN,16,7,0,-4.13,0.5,0.00,0.0,-2.63,NaN,NaN
11148507,2,2024-12-31 23:05:00,2024-12-31 23:18:00,NaN,4.56,NaN,252,16,0,-1.68,0.5,0.00,0.0,-0.18,NaN,NaN
11148508,2,2024-12-31 23:03:16,2024-12-31 23:28:35,NaN,3.94,NaN,181,255,0,4.46,0.5,5.19,0.0,11.15,NaN,NaN
11148509,1,2024-12-31 23:15:33,2024-12-31 23:36:29,NaN,4.20,NaN,165,61,0,27.07,0.5,0.00,0.0,28.57,NaN,NaN
11148510,2,2024-12-31 23:04:36,2024-12-31 23:33:34,NaN,5.76,NaN,225,114,0,2.17,0.5,0.00,0.0,6.17,NaN,NaN

In [41]:
# Drop duplicate rows
quarters4_ytaxi.drop_duplicates(inplace=True)
print(f"\nNumber of rows after dropping duplicates: {quarters4_ytaxi.shape[0]}")

# Handle missing values in 'passenger_count' and 'RatecodeID' by filling with the mode
for col in ['passenger_count', 'RatecodeID']:
    if quarters4_ytaxi[col].isnull().any():
        mode_value = quarters4_ytaxi[col].mode()[0]
        quarters4_ytaxi[col] = quarters4_ytaxi[col].fillna(mode_value)
        print(f"Filled missing values in '{col}' with mode: {mode_value}")

# Handle missing values in 'congestion_surcharge' and 'Airport_fee' by dropping rows
cols_to_drop_na = ['congestion_surcharge', 'Airport_fee']
quarters4_ytaxi.dropna(subset=cols_to_drop_na, inplace=True)
print(f"Number of rows after dropping rows with missing values in {cols_to_drop_na}: {quarters4_ytaxi.shape[0]}")

# Verify that there are no more missing values in the handled columns
print("\nMissing values after handling:")
print(quarters4_ytaxi[['passenger_count', 'RatecodeID', 'congestion_surcharge', 'Airport_fee']].isnull().sum())

Number of rows after dropping duplicates: 11148509
Filled missing values in 'passenger_count' with mode: 1.0
Filled missing values in 'RatecodeID' with mode: 1.0
Number of rows after dropping rows with missing values in ['congestion_surcharge', 'Airport_fee']: 10054649

Missing values after handling:
passenger_count         0
RatecodeID              0
congestion_surcharge    0
Airport_fee             0
dtype: int64

In [42]:
quarters4_ytaxi

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,mta_tax,tip_amount,tolls_amount,total_amount,congestion_surcharge,Airport_fee
0,2,2024-10-01 00:30:44,2024-10-01 00:48:26,1.0,3.00,1.0,162,246,1,18.4,0.5,1.50,0.0,24.90,2.5,0.00
1,1,2024-10-01 00:12:20,2024-10-01 00:25:25,1.0,2.20,1.0,48,236,1,14.2,0.5,3.80,0.0,23.00,2.5,0.00
2,1,2024-10-01 00:04:46,2024-10-01 00:13:52,1.0,2.70,1.0,142,24,1,13.5,0.5,3.70,0.0,22.20,2.5,0.00
3,1,2024-10-01 00:12:10,2024-10-01 00:23:01,1.0,3.10,1.0,233,75,1,14.2,0.5,2.00,0.0,21.20,2.5,0.00
4,1,2024-10-01 00:30:22,2024-10-01 00:30:39,1.0,0.00,1.0,262,262,3,3.0,0.5,0.00,0.0,8.00,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10822215,2,2024-12-31 22:56:33,2024-12-31 23:05:57,1.0,1.90,1.0,237,262,1,12.1,0.5,1.88,0.0,18.98,2.5,0.00
10822216,2,2024-12-31 23:18:37,2024-12-31 23:32:32,1.0,3.88,1.0,237,226,2,19.1,0.5,0.00,0.0,24.10,2.5,0.00
10822217,2,2024-12-31 23:08:52,2024-12-31 23:34:59,1.0,5.53,1.0,142,255,1,29.6,0.5,2.00,0.0,36.60,2.5,0.00
10822218,2,2024-12-31 23:15:55,2024-12-31 23:24:24,1.0,0.89,1.0,43,48,1,9.3,0.5,2.14,0.0,16.44,2.5,0.00
10822219,2,2024-12-31 23:13:22,2024-12-31 23:49:57,1.0,20.49,1.0,132,33,1,77.9,0.5,10.00,0.0,92.15,0.0,1.75

## Explore Data

In [15]:
# Descriptive statistics

# Data visualization
# Target variable analysis: examine how each feature correlates with or impacts the target/interested variable

## Data Modeling

In [16]:
# Partition data

# Handle imbalance data (optional)

# Model selection and tuning

# Evaluate models

#### สรุปผลที่ได้
...

-----------------
# เสร็จแล้ววววว 🥳

สิ่งที่ต้องแนบส่ง:
* Notebook File (ตัวอย่าง "filename.ipynb") หรือ Link to Google Colab / GitHub ซึ่งมีผลลัพธ์จากการรันโค้ดแสดงทั้งหมด
* Slides สำหรับการนำเสนอ **10** นาที ซึ่งประกอบไปด้วย
    * Data Description: อธิบายข้อมูลที่ใช้
    * Data Preparation: การเตรียมข้อมูลก่อนวิเคราะห์
    * Motivation: ปัญหาหรือคำถามที่ตั้ง ทำไมถึงสนใจที่จะทำงานในเรื่องนี้
    * Communicating Results (with figure, table, etc.): ผลที่ได้จากการศึกษา โดยระบุแนวทางที่ใช้ที่ทำให้เกิดผลลัพธ์ดังกล่าวด้วย
        โดยไม่ต้องนำเสนอ source code ผลประกอบด้วย 2 ส่วนสำคัญ จาก
        * Conjectures >= 3 ข้อ
        * Machine learning models
    * Conclusion: สรุปผลที่ได้จากการวิเคราะห์ข้อมูล
** Note: แต่ละกลุ่มส่งแต่ละไฟล์ครั้งเดียว **
---------------------